Imports System.IO
Imports System.Runtime.CompilerServices
Imports System.Text.Json
Imports Microsoft.Xna.Framework

''' <summary>
''' Contains essential constants, functions, enums, etc. used throughout the game.
''' </summary>
Public Module Essentials
#Region "Constants"
    Public Const SCREEN_WIDTH As Integer = 540
    Public Const SCREEN_HEIGHT As Integer = 960
    Public Const MAZE_WIDTH As Integer = 19
    Public Const MAZE_HEIGHT As Integer = 21
    Public Const CELL_SIZE As Integer = 24
    Public Const ICON_SIZE As Integer = 12
    Public Const PAUSE_BUTTON_SCALE As Integer = 2

    Public Const PLAYER_SIZE As Integer = 20
    Public Const SEED_SIZE As Integer = 12
    Public Const ENEMY_SIZE As Integer = 20
    Public Const PLAYER_SPEED As Single = 100.0F
    Public Const ENEMY_SPEED As Single = 80.0F
    Public Const VULNERABLE_DURATION As Single = 8.0F
    Public Const ENEMY_RESPAWN_TIME As Single = 5.0F
    Public Const ENEMY_GRACE_PERIOD As Single = 2.0F
    Public Const GET_READY_DURATION As Single = 5.0F
    Public Const NEXT_LEVEL_DURATION As Single = 2.0F
    Public Const LEVEL_CLEARED_DURATION As Single = 3.5F
    Public Const DEATH_ANIMATION_DURATION As Single = 2.0F

    Public Const STARTING_LIVES As Integer = 3
    Public Const SEED_POINTS As Integer = 10
    Public Const ENEMY_POINTS As Integer = 200
    Public Const PESTICIDE_POINTS As Integer = 50
    Public Const BONUS_LIFE_AT As Integer = 7000

    Public ReadOnly Property PlayerStartingPoint As New Point(MAZE_WIDTH \ 2, MAZE_HEIGHT - 2)
#End Region

#Region "Enums"
    ''' <summary>
    ''' Represents the current state of the game.
    ''' </summary>
    Public Enum GameState As Integer
        Title = 0
        Playing = 1
        Paused = 2
        GameOver = 3
        LevelStart = 4
        LevelCleared = 5
    End Enum

    ''' <summary>
    ''' Represents the type of a tile in the maze.
    ''' </summary>
    Public Enum MazeTile As Integer
        Walkable = 0
        Collectible = 1
        Pesticide = 2
        Sapling = 3
        Tree = 4
        Fence = 5
        Enemy = 6
    End Enum

    ''' <summary>
    ''' Represents the direction of movement.
    ''' </summary>
    Public Enum Direction As Integer
        Up = 0
        Down = 1
        Left = 2
        Right = 3
    End Enum

    ''' <summary>
    ''' Represents the type of a seed.
    ''' </summary>
    Public Enum SeedType As Integer
        Acorn = 0
        Berry = 1
        Nut = 2
    End Enum

    ''' <summary>
    ''' Represents the type of an enemy.
    ''' </summary>
    Public Enum EnemyType As Integer
        Beetle = 0
        Caterpillar = 1
    End Enum
#End Region

#Region "Events / Signals"
    ' NOTE: Scheduling methods for these events were all auto-generated by the source generator
    '       known as `ModuleEventRaiser.Generator`.
    Public Event GameStateChanged(newState As GameState)
    Public Event PlayerScoreChanged(score As Integer)
    Public Event HighScoreChanged(highScore As Integer)
    Public Event LivesChanged(lives As Integer)
    Public Event LevelChanged(level As Integer)
    Public Event SeedCollected(seed As Actor.Seed)
    Public Event PesticideCollected()
    Public Event EnemyKilled(enemy As Actor.Enemy)
    Public Event EnemyRespawned(enemy As Actor.Enemy)
    Public Event GameHasEnded()
    Public Event LifeLost()
    Public Event LevelCleared()
    Public Event GetReadyMessage()
    Public Event GameStart()
    Public Event GameHasBegun()
    Public Event DeathAnimationComplete()
    Public Event MovingToNextLevel()
    Public Event TreeGrown(position As Point)
#End Region

#Region "Functions and Properties"
    ''' <summary>
    ''' Calculates the Manhattan distance between two points.
    ''' </summary>
    ''' <param name="pt1">The first point.</param>
    ''' <param name="pt2">The second point.</param>
    ''' <returns>The Manhattan distance between the two points.</returns>
    Public Function ManhattanDistance(pt1 As Point, pt2 As Point) As Integer
        Return Math.Abs(pt1.X - pt2.X) + Math.Abs(pt1.Y - pt2.Y)
    End Function

    ''' <summary>
    ''' Checks if a point (e.g., mouse click or touch position) is within a rectangular area.
    ''' Primarily used for button interaction detection in the game UI.
    ''' </summary>
    ''' <param name="point">The point to check (typically a mouse or touch position).</param>
    ''' <param name="rect">The rectangular area to check against (typically a button bounds).</param>
    ''' <returns>True if the point is within the rectangle, False otherwise.</returns>
    Public Function IsPointInRect(point As Vector2, rect As Rectangle) As Boolean
        Return point.X >= rect.X AndAlso point.X <= rect.X + rect.Width AndAlso
               point.Y >= rect.Y AndAlso point.Y <= rect.Y + rect.Height
    End Function

    ''' <summary>
    ''' Converts a direction enum to a Vector2.
    ''' </summary>
    ''' <param name="direction">The direction enum to convert.</param>
    ''' <returns>A Vector2 representing the direction.</returns>
    <Extension> Public Function ToVector2(direction As Direction) As Vector2
        Select Case direction
            Case Direction.Up
                Return New Vector2(0, -1)
            Case Direction.Down
                Return New Vector2(0, 1)
            Case Direction.Left
                Return New Vector2(-1, 0)
            Case Direction.Right
                Return New Vector2(1, 0)
        End Select
    End Function

    ''' <summary>
    ''' Creates a maze layout with everything needed, using a specific algorithm.
    ''' </summary>
    ''' <remarks>
    ''' <para>The maze layout contains:</para>
    ''' <list type="number">
    ''' <item><description>Fences (5) around the perimeter</description></item>
    ''' <item><description>Walkable tiles (0) forming continuous paths</description></item>
    ''' <item><description>Saplings (3) in a checkerboard pattern</description></item>
    ''' <item><description>No dead ends or enclosed spaces</description></item>
    ''' </list>
    ''' </remarks>
    ''' <param name="level">The current level number.</param>
    ''' <returns>A complete maze layout.</returns>
    Public Function CreateMazeLayout(level As Integer) As MazeTile(,)
        Dim maze(MAZE_WIDTH - 1, MAZE_HEIGHT - 1) As MazeTile
        Dim maxRowIndex = MAZE_WIDTH - 1
        Dim maxColIndex = MAZE_HEIGHT - 1
        Dim saplingCount = 0, seedCount = 0

        For i As Integer = 0 To maxRowIndex
            For j As Integer = 0 To maxColIndex
                ' Fences around the perimeter
                If i = 0 OrElse i = maxRowIndex OrElse j = 0 OrElse j = maxColIndex Then
                    maze(i, j) = MazeTile.Fence
                    Continue For
                End If

                ' Second and second-to-last rows are all walkable (border paths)
                If i = 1 OrElse i = maxRowIndex - 1 Then
                    maze(i, j) = MazeTile.Walkable
                    Continue For
                End If
                ' First and last columns of inner area are walkable (border paths)
                If j = 1 OrElse j = maxColIndex - 1 Then
                    maze(i, j) = MazeTile.Walkable
                    Continue For
                End If

                If i Mod 2 = 0 AndAlso j Mod 2 = 0 Then
                    maze(i, j) = MazeTile.Sapling
                    saplingCount += 1
                    seedCount += 1
                Else
                    maze(i, j) = MazeTile.Walkable
                End If
            Next j
        Next i

        Dim enemyCount = Math.Clamp(level + 4, 5, 12)
        Dim rnd = Random.Shared
        Const PESTICIDE_COUNT = 4

        Dim playerStart = PlayerStartingPoint
        Dim GetWalkableTiles =
            Function()
                Dim tiles As New List(Of Point)
                For i As Integer = 0 To maxRowIndex
                    For j As Integer = 0 To maxColIndex
                        If maze(i, j) = MazeTile.Walkable AndAlso
                            Not (i = playerStart.X AndAlso j = playerStart.Y) Then
                            tiles.Add(New Point(i, j))
                        End If
                    Next j
                Next i
                Return tiles
            End Function

        Dim seedTiles = From wt In GetWalkableTiles()
                        Where ManhattanDistance(wt, playerStart) > 1
                        Order By rnd.Next() Take seedCount
        For Each tile In seedTiles
            maze(tile.X, tile.Y) = MazeTile.Collectible
        Next tile

        Dim farTiles = From wt In GetWalkableTiles()
                       Where ManhattanDistance(wt, playerStart) > 5
                       Order By rnd.Next() Take PESTICIDE_COUNT
        For Each tile In farTiles
            maze(tile.X, tile.Y) = MazeTile.Pesticide
        Next tile

        Dim enemyTiles = From wt In GetWalkableTiles()
                         Where ManhattanDistance(wt, playerStart) > 5
                         Order By rnd.Next() Take enemyCount
        For Each tile In enemyTiles
            maze(tile.X, tile.Y) = MazeTile.Enemy
        Next tile

        Return maze
    End Function

    ''' <summary>
    ''' Determines the seed type for the current level.
    ''' </summary>
    ''' <param name="level">The current level number.</param>
    ''' <returns>The seed type for the current level.</returns>
    Public ReadOnly Property SeedTypeForLevel(level As Integer) As SeedType
        Get
            Select Case (level - 1) Mod 3
                Case 0
                    Return SeedType.Acorn
                Case 1
                    Return SeedType.Berry
                Case 2
                    Return SeedType.Nut
                Case Else
                    Return 0
            End Select
        End Get
    End Property

    ''' <summary>
    ''' Determines the enemy type for the current level.
    ''' </summary>
    ''' <param name="level">The current level number.</param>
    ''' <returns>The enemy type for the current level.</returns>
    Public ReadOnly Property EnemyTypeForLevel(level As Integer) As EnemyType
        Get
            Select Case (level - 1) Mod 2
                Case 0
                    Return EnemyType.Beetle
                Case 1
                    Return EnemyType.Caterpillar
                Case Else
                    Return 0
            End Select
        End Get
    End Property

    ''' <summary>
    ''' Gets the full path to the high score file.
    ''' </summary>
    ''' <returns>The full file path.</returns>
    Private ReadOnly Property HighScoreFilePath As String
        Get
            Const HIGH_SCORE_FILE As String = "high_score.json"
            Dim appDataPath = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData)
            Dim gameFolderPath As String = Path.Combine(appDataPath, "SeedScape")
            If Not Directory.Exists(gameFolderPath) Then Directory.CreateDirectory(gameFolderPath)
            Return Path.Combine(gameFolderPath, HIGH_SCORE_FILE)
        End Get
    End Property

    ''' <summary>
    ''' Saves the high score to a JSON file.
    ''' </summary>
    ''' <param name="highScore">The high score to save.</param>
    Public Sub SaveHighScore(highScore As Integer)
        Try
            Dim json As String = JsonSerializer.Serialize(highScore)
            File.WriteAllText(HighScoreFilePath, json)
        Catch
        End Try
    End Sub

    ''' <summary>
    ''' Loads the high score from a JSON file.
    ''' </summary>
    ''' <returns>The loaded high score, or 0 if no file exists or an error occurs.</returns>
    Public Function LoadHighScore() As Integer
        Dim filePath = HighScoreFilePath
        Try
            If File.Exists(filePath) Then
                Dim json As String = File.ReadAllText(filePath)
                Return JsonSerializer.Deserialize(Of Integer)(json)
            End If
        Catch
        End Try
        Return 0
    End Function
#End Region
End Module